version: "3.8"

services:
  app:
    container_name: fastapi-trade-app
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env  # Loads DATABASE_URL at runtime
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: always